### ISSUE TITLE
Vagrant SCP commands don't work

### ISSUE THREAD

**Issue by tarunlalwani** [rimusz/coreos-osx-gui-kubernetes-cluster#23]
I think vagrant cli has changed a bit and it needs the name of the node as well

``` shell
control $ vagrant scp master.tgz /home/core/
/opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /usr in PATH, mode 040777
/opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /usr in PATH, mode 040777
The machine with the name 'default' was not found configured for
this Vagrant environment.
```

But when I do that i get another error

``` shell
control $ vagrant scp master.tgz k8smaster-01:/home/core/
/opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /usr in PATH, mode 040777
/opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /usr in PATH, mode 040777
/opt/vagrant/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:359:in `block (3 levels) in start_command': SCP did not finish successfully (1) (Net::SCP::Error)
    from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:591:in `call'
    from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:591:in `do_close'
    from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:587:in `channel_close'
    from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:466:in `dispatch_incoming_packets'
    from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:222:in `preprocess'
    from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
    from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
    from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
    from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
    from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:119:in `close'
    from /opt/vagrant/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:205:in `ensure in start'
    from /opt/vagrant/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:205:in `start'
    from /opt/vagrant/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:221:in `upload!'
    from /Users/tarunlalwani/.vagrant.d/gems/gems/vagrant-scp-0.5.0/lib/vagrant/scp/commands/scp.rb:21:in `block in execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/plugin/v2/command.rb:220:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    from /Users/tarunlalwani/.vagrant.d/gems/gems/vagrant-scp-0.5.0/lib/vagrant/scp/commands/scp.rb:17:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/environment.rb:301:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/bin/vagrant:174:in `<main>'
```

I am using Vagrant 1.7.3

**Comment by rimusz** [comment]
fixed in the lastest v0.5.2
